# Generated by Django 3.0.4 on 2020-03-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200322_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquetext',
            name='textlabel',
            field=models.TextField(),
        ),
    ]
